export const hobbies = {
  'Animation': false,
  'Aquarium': false,
  'Astronomy': false,
  'Birdwatching': true,
  'Blood Donation': false,
  'Botanics': false,
  'Calligraphy': false,
  'Camping': false,
  'Clothing design': false,
  'Cooking': false,
  'Dancing': false,
  'Diving': false,
  'DIY Postcards': false,
  'Drawing': false,
  'Electric guitar': false,
  'Electronics': false,
  'Foraging': false,
  'Gaming': false,
  'Gardening': false,
  'Hang out with friends': true,
  'Juggling': false,
  'Knitting': false,
  'Lego': false,
  'Machine Learning': false,
  'Make-up art': false,
  'Martial art': false,
  'Model figures': false,
  'Music Instrument': false,
  'Performance poi': false,
  'Pet-project': true,
  'Photography': false,
  'Pottery': false,
  'Puzzles': false,
  'Roller-skates': false,
  'Rope Park': false,
  'Running': true,
  'Self-sustaining terrarium': false,
  'Serbian': true,
  'Sewing': false,
  'Shibari': false,
  'Singing': false,
  'Skating': true,
  'Slackline': false,
  'Street-art': false,
  'Teas': false,
  'Terrarium': false,
  'Via Ferrata': false,
  'Volunteering': false,
  'Woodworking': false,
  'Yachting': false,
  'Yoga': false,
}
