export const hobbies = {
  'Skating': true,
  'Birdwatching': false,
  'Serbian': false,
  'Diving': false,
  'Performance poi': false,
  'Shibari': false,
  'Model figures': false,
  'Make-up art': false,
  'Singing': false,
  'Dancing': false,
  'Gaming': false,
  'Pet-project': false,
  'Yachting': false,
  'Animation': false,
  'Hang out with friends': false,
  'Street-art': false,
  'Slackline': false,
  'Roller-scates': false,
  'Via Ferrata': false,
  'Camping': false,
  'Woodworking': false,
  'Gardening': false,
  'Self-sustained terrarium': false,
  'DIY Postcards': false,
  'Yoga': false,
  'Rope Park': false,
  'Clothing design': false,
  'Martial art': false,
  'Calligraphy': false,
}
